name: Build docker images

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: docker build -t canghai/toolbox:latest .
    - run: docker login -u $DOCKERHUB_LOGIN_USER -p $DOCKERHUB_LOGIN_PASSWORD
      
