name: Build docker images

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: pwd
    - run: ls
    - run: whoami
    - run: hostname
    - run: docker info
    - run: docker build -t canghai/toolbox .
      
