name: Build docker images

on:
  push:
    branches: [master]

jobs:
  build:
    env:
      DOCKERHUB_LOGIN_USER: ${{ secret.DOCKERHUB_LOGIN_USER }}
      DOCKERHUB_LOGIN_PASSWORD:  ${{ secret.DOCKERHUB_LOGIN_PASSWORD }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: docker build -t canghai/toolbox:latest .
    - run: docker login -u "$DOCKERHUB_LOGIN_USER" -p "$DOCKERHUB_LOGIN_PASSWORD"
      
