name: Build docker image

on:
  push:
    branches: [master]

jobs:
  build:
    env:
      DOCKERHUB_LOGIN_USER: ${{ secrets.DOCKERHUB_LOGIN_USER }}
      DOCKERHUB_LOGIN_PASSWORD:  ${{ secrets.DOCKERHUB_LOGIN_PASSWORD }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker build
      run: docker build -t canghai/toolbox:latest .
    - name: Docker login
      run: docker login -u "$DOCKERHUB_LOGIN_USER" -p "$DOCKERHUB_LOGIN_PASSWORD"
    - name: Docker push
      run: docker push canghai/toolbox:latest
